import request from './http'

export const loginApi = (payload) => request.post('/auth/login', payload)
export const logoutApi = () => request.post('/auth/logout')
export const getDashboardSummary = (deviceCode) => request.get('/dashboard/summary', { params: { deviceCode } })
export const getDispatchAdvice = (deviceCode) => request.get('/dashboard/dispatch-advice', { params: { deviceCode } })
export const getForecast = (deviceCode) => request.get('/dashboard/forecast', { params: { deviceCode } })
export const postDispatchDecision = (payload) => request.post('/dashboard/dispatch-advice/decision', payload)
export const getLatestSensor = (deviceCode) => request.get(`/sensor/latest/${deviceCode}`)
export const getSensorHistory = (deviceCode, hours = 24) => request.get(`/sensor/history/${deviceCode}`, { params: { hours } })
export const getSensorHistoryPage = (deviceCode, params = {}) => request.get(`/sensor/history/${deviceCode}`, { params })
export const getDevices = (params) => request.get('/devices', { params })
export const getDeviceDetail = (id) => request.get(`/devices/${id}`)
export const getDeviceFaultHistory = (id) => request.get(`/devices/${id}/fault-history`)
export const getDeviceHealthScore = (id) => request.get(`/devices/${id}/health-score`)
export const createDevice = (payload) => request.post('/devices', payload)
export const updateDevice = (id, payload) => request.put(`/devices/${id}`, payload)
export const deleteDevice = (id) => request.delete(`/devices/${id}`)
export const getWorkOrders = (status) => request.get('/work-orders', { params: { status } })
export const updateWorkOrderStatus = (id, payload) => request.patch(`/work-orders/${id}/status`, payload)
export const getActiveAlerts = (limit = 5) => request.get('/work-orders/active-alerts', { params: { limit } })
export const listUsers = (params) => request.get('/users', { params })
export const createUser = (payload) => request.post('/users', payload)
export const updateUser = (id, payload) => request.put(`/users/${id}`, payload)
export const updateUserStatus = (id, status) => request.patch(`/users/${id}/status`, null, { params: { status } })
export const deleteUser = (id) => request.delete(`/users/${id}`)
export const listAuditLogs = (params) => request.get('/audit-logs', { params })

// ============ Epic 07：维修知识库 & 备件管理 ============
// SOP
export const listSops = (params) => request.get('/sops', { params })
export const getSop = (id) => request.get(`/sops/${id}`)
export const createSop = (payload) => request.post('/sops', payload)
export const updateSop = (id, payload) => request.put(`/sops/${id}`, payload)
export const deleteSop = (id) => request.delete(`/sops/${id}`)
// 维修案例
export const listCases = (params) => request.get('/cases', { params })
export const getCase = (id) => request.get(`/cases/${id}`)
export const createCase = (payload) => request.post('/cases', payload)
export const updateCase = (id, payload) => request.put(`/cases/${id}`, payload)
export const deleteCase = (id) => request.delete(`/cases/${id}`)
// 知识图谱
export const getKnowledgeGraph = (params) => request.get('/knowledge/graph', { params })
// 维修建议
export const getRepairAdvice = (payload) => request.post('/ai/repair-advice', payload)
// 备件管理
export const listSpareParts = (params) => request.get('/spare-parts', { params })
export const getSparePart = (id) => request.get(`/spare-parts/${id}`)
export const createSparePart = (payload) => request.post('/spare-parts', payload)
export const updateSparePart = (id, payload) => request.put(`/spare-parts/${id}`, payload)
export const deleteSparePart = (id) => request.delete(`/spare-parts/${id}`)
export const recordSparePartUsage = (payload) => request.post('/spare-parts/usage', payload)
export const recordSparePartUsages = (items) => request.post('/spare-parts/usage/batch', { items })
export const listSparePartUsages = (params) => request.get('/spare-parts/usage', { params })
