server:
  port: 8080 # ?????????

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_energy
    username: energy_user
    password: energy_password
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.smartenergy.backend.entity
  global-config:
    db-config:
      # ????????????
      id-type: auto
  configuration:
    # ??????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl